name: FOSSology License Scan

on:
  push:
    branches:
      - main

jobs:
  license_scan:
    runs-on: ubuntu-latest
    name: Run FOSSology scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compliance check
        uses: fossology/fossology-action@v1
        continue-on-error: true
        with:
          scan_mode: 'repo'
          scanners: 'nomos ojo copyright keyword'
          report_format: 'TEXT'
          allowlist_file_path: 'allowlist.json'

      - name: Prepare for SPDX report
        run: |
          rm -rf results/
          mv allowlist.json allowlist.json.bak

      - name: Generate SPDX report
        uses: fossology/fossology-action@v1
        continue-on-error: true
        with:
          scan_mode: 'repo'
          scanners: 'nomos ojo copyright keyword'
          report_format: 'SPDX_JSON'

      - name: Restore allowlist
        run: mv allowlist.json.bak allowlist.json

      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fossology-report
          path: results/