

name: Software Composition Analysis

on:
  push:


permissions:
  contents: read
  actions: write

jobs:
  sca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run FOSSology analysis
        id: fossology
        uses: shatakshisgtiwari-jpg/fossology-action@main
        with:
          scan_mode: "repo-scan"
          scanners: "nomos ojo copyright keyword"
          report_format: "SPDX_JSON"
          dashboard: true
          dashboard_charts: true
          dashboard_risk: true
          dashboard_unknown: true

      - name: Upload Scan Results Artifact
        if: success() || failure()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Fossology scan results
          path: results/

